package mod.akrivus.kagic.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;

public class ModSounds {
	public static final SoundEvent RECORD_LITTLE_PERIDOT = new SoundEvent(new ResourceLocation("kagic:records.little_peridot"));
	public static final SoundEvent RECORD_ROSES_FOUNTAIN = new SoundEvent(new ResourceLocation("kagic:records.roses_fountain"));
	public static final SoundEvent RECORD_LAPIS_FLIGHT = new SoundEvent(new ResourceLocation("kagic:records.lapis_flight"));
	public static final SoundEvent RECORD_THE_BREAKING_POINT = new SoundEvent(new ResourceLocation("kagic:records.the_breaking_point"));
	public static final SoundEvent RECORD_DUEL_OF_THE_QUARTZ = new SoundEvent(new ResourceLocation("kagic:records.duel_of_the_quartz"));
	public static final SoundEvent RECORD_YELLOW_DIAMOND = new SoundEvent(new ResourceLocation("kagic:records.yellow_diamond"));
	public static final SoundEvent RECORD_BLUE_DIAMOND = new SoundEvent(new ResourceLocation("kagic:records.blue_diamond"));
	public static final SoundEvent RECORD_WHATS_THE_USE_OF_FEELING_BLUE = new SoundEvent(new ResourceLocation("kagic:records.whats_the_use_of_feeling_blue"));
	public static final SoundEvent RECORD_LOVE_LIKE_YOU = new SoundEvent(new ResourceLocation("kagic:records.love_like_you"));
	
	public static final SoundEvent RECORD_HEAVEN_BEETLE = new SoundEvent(new ResourceLocation("kagic:records.heaven_beetle"));
	public static final SoundEvent RECORD_DEFECTIVE = new SoundEvent(new ResourceLocation("kagic:records.defective"));
	public static final SoundEvent RECORD_GEM_SHARDS = new SoundEvent(new ResourceLocation("kagic:records.gem_shards"));
	public static final SoundEvent RECORD_HEART_OF_THE_PYRAMID = new SoundEvent(new ResourceLocation("kagic:records.pyramid"));
	public static final SoundEvent RECORD_UNDERWATER_TEMPLE = new SoundEvent(new ResourceLocation("kagic:records.underwater_temple"));
	
	public static final SoundEvent BLOCK_GEM_SEED_HATCH = new SoundEvent(new ResourceLocation("kagic:blocks.gem_seed_hatch"));
	public static final SoundEvent BLOCK_INJECTOR_OPEN = new SoundEvent(new ResourceLocation("kagic:blocks.injector_open"));
	public static final SoundEvent BLOCK_INJECTOR_CLOSE = new SoundEvent(new ResourceLocation("kagic:blocks.injector_close"));
	public static final SoundEvent BLOCK_INJECTOR_FIRE = new SoundEvent(new ResourceLocation("kagic:blocks.injector_fire"));
	public static final SoundEvent GEM_POOF = new SoundEvent(new ResourceLocation("kagic:entities.gem.poof"));
	public static final SoundEvent GEM_SHATTER = new SoundEvent(new ResourceLocation("kagic:entities.gem.shatter"));

	public static final SoundEvent SLAG_EAT = new SoundEvent(new ResourceLocation("kagic:entities.slag.eat"));
	public static final SoundEvent SLAG_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.slag.living"));
	public static final SoundEvent PEPO_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.pepo.living"));
	public static final SoundEvent RUBY_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.ruby.living"));
	public static final SoundEvent RUBY_HURT = new SoundEvent(new ResourceLocation("kagic:entities.ruby.hurt"));
	public static final SoundEvent RUBY_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.ruby.obey"));
	public static final SoundEvent RUBY_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.ruby.death"));
	public static final SoundEvent RUBY_EXPLODE = new SoundEvent(new ResourceLocation("kagic:entities.ruby.explode"));
	public static final SoundEvent SAPPHIRE_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.living"));
	public static final SoundEvent SAPPHIRE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.hurt"));
	public static final SoundEvent SAPPHIRE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.obey"));
	public static final SoundEvent SAPPHIRE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.death"));
	public static final SoundEvent PADPARADSCHA_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.padparadscha.living"));
	public static final SoundEvent PERIDOT_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.peridot.living"));
	public static final SoundEvent PERIDOT_HURT = new SoundEvent(new ResourceLocation("kagic:entities.peridot.hurt"));
	public static final SoundEvent PERIDOT_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.peridot.obey"));
	public static final SoundEvent PERIDOT_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.peridot.death"));
	public static final SoundEvent PEARL_HURT = new SoundEvent(new ResourceLocation("kagic:entities.pearl.hurt"));
	public static final SoundEvent PEARL_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.pearl.obey"));
	public static final SoundEvent PEARL_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.pearl.death"));
	public static final SoundEvent BISMUTH_HURT = new SoundEvent(new ResourceLocation("kagic:entities.bismuth.hurt"));
	public static final SoundEvent BISMUTH_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.bismuth.obey"));
	public static final SoundEvent BISMUTH_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.bismuth.death"));
	public static final SoundEvent JASPER_HURT = new SoundEvent(new ResourceLocation("kagic:entities.jasper.hurt"));
	public static final SoundEvent JASPER_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.jasper.obey"));
	public static final SoundEvent JASPER_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.jasper.death"));
	public static final SoundEvent AMETHYST_HURT = new SoundEvent(new ResourceLocation("kagic:entities.amethyst.hurt"));
	public static final SoundEvent AMETHYST_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.amethyst.obey"));
	public static final SoundEvent AMETHYST_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.amethyst.death"));
	public static final SoundEvent ROSE_QUARTZ_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.living"));
	public static final SoundEvent ROSE_QUARTZ_HURT = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.hurt"));
	public static final SoundEvent ROSE_QUARTZ_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.obey"));
	public static final SoundEvent ROSE_QUARTZ_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.death"));
	public static final SoundEvent LAPIS_LAZULI_HURT = new SoundEvent(new ResourceLocation("kagic:entities.lapis_lazuli.hurt"));
	public static final SoundEvent LAPIS_LAZULI_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.lapis_lazuli.obey"));
	public static final SoundEvent LAPIS_LAZULI_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.lapis_lazuli.death"));
	public static final SoundEvent AGATE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.agate.hurt"));
	public static final SoundEvent AGATE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.agate.obey"));
	public static final SoundEvent AGATE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.agate.death"));
	public static final SoundEvent YELLOW_DIAMOND_INTRO = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.intro"));
	public static final SoundEvent YELLOW_DIAMOND_OUTRO = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.outro"));
	public static final SoundEvent YELLOW_DIAMOND_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.living"));
	public static final SoundEvent YELLOW_DIAMOND_HURT = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.hurt"));
	public static final SoundEvent YELLOW_DIAMOND_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.death"));
	public static final SoundEvent BLUE_DIAMOND_INTRO = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.intro"));
	public static final SoundEvent BLUE_DIAMOND_OUTRO = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.outro"));
	public static final SoundEvent BLUE_DIAMOND_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.living"));
	public static final SoundEvent BLUE_DIAMOND_HURT = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.hurt"));
	public static final SoundEvent BLUE_DIAMOND_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.death"));
	public static final SoundEvent AQUAMARINE_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.living"));
	public static final SoundEvent AQUAMARINE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.hurt"));
	public static final SoundEvent AQUAMARINE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.obey"));
	public static final SoundEvent AQUAMARINE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.death"));
	public static final SoundEvent GARNET_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.garnet.death"));
	public static final SoundEvent GARNET_HURT = new SoundEvent(new ResourceLocation("kagic:entities.garnet.hurt"));
	public static final SoundEvent GARNET_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.garnet.obey"));
	public static final SoundEvent HESSONITE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.hessonite.death"));
	public static final SoundEvent HESSONITE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.hessonite.hurt"));
	public static final SoundEvent HESSONITE_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.hessonite.living"));
	public static final SoundEvent HESSONITE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.hessonite.obey"));
	public static final SoundEvent HESSONITE_TELEPORT_START = new SoundEvent(new ResourceLocation("kagic:entities.hessonite.teleport.start"));
	public static final SoundEvent HESSONITE_TELEPORT_END = new SoundEvent(new ResourceLocation("kagic:entities.hessonite.teleport.end"));
	public static final SoundEvent MALACHITE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.malachite.death"));
	public static final SoundEvent MALACHITE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.malachite.hurt"));
	public static final SoundEvent MALACHITE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.malachite.obey"));
	public static final SoundEvent RHODONITE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.rhodonite.death"));
	public static final SoundEvent RHODONITE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.rhodonite.hurt"));
	public static final SoundEvent RHODONITE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.rhodonite.obey"));
	public static final SoundEvent RUTILE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.rutile.death"));
	public static final SoundEvent RUTILE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.rutile.hurt"));
	public static final SoundEvent RUTILE_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.rutile.living"));
	public static final SoundEvent RUTILE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.rutile.obey"));
	public static final SoundEvent TOPAZ_STEP = new SoundEvent(new ResourceLocation("kagic:entities.topaz.step"));
	public static final SoundEvent TOPAZ_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.topaz.obey"));
	public static final SoundEvent TOPAZ_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.topaz.death"));
	public static final SoundEvent ZIRCON_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.zircon.death"));
	public static final SoundEvent ZIRCON_HURT = new SoundEvent(new ResourceLocation("kagic:entities.zircon.hurt"));
	public static final SoundEvent ZIRCON_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.zircon.obey"));
	
	public static final SoundEvent STEVEN_HELLO = new SoundEvent(new ResourceLocation("kagic:entities.steven.hello"));
	public static final SoundEvent STEVEN_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.steven.living"));
	public static final SoundEvent STEVEN_HURT = new SoundEvent(new ResourceLocation("kagic:entities.steven.hurt"));
	public static final SoundEvent STEVEN_PROTECT = new SoundEvent(new ResourceLocation("kagic:entities.steven.protect"));
	public static final SoundEvent STEVEN_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.steven.death"));
	public static final SoundEvent STEVEN_SNEEZE = new SoundEvent(new ResourceLocation("kagic:entities.steven.sneeze"));
	public static final SoundEvent CONNIE_HELLO = new SoundEvent(new ResourceLocation("kagic:entities.connie.hello"));
	public static final SoundEvent CONNIE_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.connie.living"));
	public static final SoundEvent CONNIE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.connie.hurt"));
	public static final SoundEvent CONNIE_PROTECT = new SoundEvent(new ResourceLocation("kagic:entities.connie.protect"));
	public static final SoundEvent CONNIE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.connie.death"));
	
	public static final SoundEvent CORRUPTED_QUARTZ_AMBIENT = new SoundEvent(new ResourceLocation("kagic:entities.corrupted_quartz.living"));
	public static final SoundEvent CORRUPTED_QUARTZ_HURT = new SoundEvent(new ResourceLocation("kagic:entities.corrupted_quartz.hurt"));
	public static final SoundEvent CORRUPTED_QUARTZ_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.corrupted_quartz.death"));
	public static final SoundEvent TONGUE_MONSTER_AMBIENT = new SoundEvent(new ResourceLocation("kagic:entities.tongue_monster.living"));
	public static final SoundEvent TONGUE_MONSTER_HURT = new SoundEvent(new ResourceLocation("kagic:entities.tongue_monster.hurt"));
	public static final SoundEvent TONGUE_MONSTER_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.tongue_monster.death"));
	
	public static final SoundEvent WARP_PAD = new SoundEvent(new ResourceLocation("kagic:blocks.warp_pad"));
	
	public static final SoundEvent[] JAM_BUD_SONG_PARTS = new SoundEvent[40];
	
	public static void registerSounds(RegistryEvent.Register<SoundEvent> event) {
		registerSound(RECORD_LITTLE_PERIDOT, new ResourceLocation("kagic:records.little_peridot"), event);
		registerSound(RECORD_ROSES_FOUNTAIN, new ResourceLocation("kagic:records.roses_fountain"), event);
		registerSound(RECORD_LAPIS_FLIGHT, new ResourceLocation("kagic:records.lapis_flight"), event);
		registerSound(RECORD_THE_BREAKING_POINT, new ResourceLocation("kagic:records.the_breaking_point"), event);
		registerSound(RECORD_DUEL_OF_THE_QUARTZ, new ResourceLocation("kagic:records.duel_of_the_quartz"), event);
		registerSound(RECORD_YELLOW_DIAMOND, new ResourceLocation("kagic:records.yellow_diamond"), event);
		registerSound(RECORD_BLUE_DIAMOND, new ResourceLocation("kagic:records.blue_diamond"), event);
		registerSound(RECORD_WHATS_THE_USE_OF_FEELING_BLUE, new ResourceLocation("kagic:records.whats_the_use_of_feeling_blue"), event);
		registerSound(RECORD_HEAVEN_BEETLE, new ResourceLocation("kagic:records.heaven_beetle"), event);
		registerSound(RECORD_DEFECTIVE, new ResourceLocation("kagic:records.defective"), event);
		registerSound(RECORD_GEM_SHARDS, new ResourceLocation("kagic:records.gem_shards"), event);
		registerSound(RECORD_HEART_OF_THE_PYRAMID, new ResourceLocation("kagic:records.pyramid"), event);
		registerSound(RECORD_LOVE_LIKE_YOU, new ResourceLocation("kagic:records.love_like_you"), event);
		registerSound(BLOCK_GEM_SEED_HATCH, new ResourceLocation("kagic:blocks.gem_seed_hatch"), event);
		registerSound(BLOCK_INJECTOR_OPEN, new ResourceLocation("kagic:blocks.injector_open"), event);
		registerSound(BLOCK_INJECTOR_CLOSE, new ResourceLocation("kagic:blocks.injector_close"), event);
		registerSound(BLOCK_INJECTOR_FIRE, new ResourceLocation("kagic:blocks.injector_fire"), event);
		registerSound(GEM_POOF, new ResourceLocation("kagic:entities.gem.poof"), event);
		registerSound(GEM_SHATTER, new ResourceLocation("kagic:entities.gem.shatter"), event);
		registerSound(SLAG_EAT, new ResourceLocation("kagic:entities.slag.eat"), event);
		registerSound(SLAG_LIVING, new ResourceLocation("kagic:entities.slag.living"), event);
		registerSound(PEPO_LIVING, new ResourceLocation("kagic:entities.pepo.living"), event);
		registerSound(RUBY_LIVING, new ResourceLocation("kagic:entities.ruby.living"), event);
		registerSound(RUBY_HURT, new ResourceLocation("kagic:entities.ruby.hurt"), event);
		registerSound(RUBY_OBEY, new ResourceLocation("kagic:entities.ruby.obey"), event);
		registerSound(RUBY_DEATH, new ResourceLocation("kagic:entities.ruby.death"), event);
		registerSound(RUBY_EXPLODE, new ResourceLocation("kagic:entities.ruby.explode"), event);
		registerSound(SAPPHIRE_LIVING, new ResourceLocation("kagic:entities.sapphire.living"), event);
		registerSound(SAPPHIRE_HURT, new ResourceLocation("kagic:entities.sapphire.hurt"), event);
		registerSound(SAPPHIRE_OBEY, new ResourceLocation("kagic:entities.sapphire.obey"), event);
		registerSound(SAPPHIRE_DEATH, new ResourceLocation("kagic:entities.sapphire.death"), event);
		registerSound(PADPARADSCHA_LIVING, new ResourceLocation("kagic:entities.padparadscha.living"), event);
		registerSound(PERIDOT_LIVING, new ResourceLocation("kagic:entities.peridot.living"), event);
		registerSound(PERIDOT_HURT, new ResourceLocation("kagic:entities.peridot.hurt"), event);
		registerSound(PERIDOT_OBEY, new ResourceLocation("kagic:entities.peridot.obey"), event);
		registerSound(PERIDOT_DEATH, new ResourceLocation("kagic:entities.peridot.death"), event);
		registerSound(PEARL_HURT, new ResourceLocation("kagic:entities.pearl.hurt"), event);
		registerSound(PEARL_OBEY, new ResourceLocation("kagic:entities.pearl.obey"), event);
		registerSound(PEARL_DEATH, new ResourceLocation("kagic:entities.pearl.death"), event);
		registerSound(BISMUTH_HURT, new ResourceLocation("kagic:entities.bismuth.hurt"), event);
		registerSound(BISMUTH_OBEY, new ResourceLocation("kagic:entities.bismuth.obey"), event);
		registerSound(BISMUTH_DEATH, new ResourceLocation("kagic:entities.bismuth.death"), event);
		registerSound(JASPER_HURT, new ResourceLocation("kagic:entities.jasper.hurt"), event);
		registerSound(JASPER_OBEY, new ResourceLocation("kagic:entities.jasper.obey"), event);
		registerSound(JASPER_DEATH, new ResourceLocation("kagic:entities.jasper.death"), event);
		registerSound(AMETHYST_HURT, new ResourceLocation("kagic:entities.amethyst.hurt"), event);
		registerSound(AMETHYST_OBEY, new ResourceLocation("kagic:entities.amethyst.obey"), event);
		registerSound(AMETHYST_DEATH, new ResourceLocation("kagic:entities.amethyst.death"), event);
		registerSound(ROSE_QUARTZ_LIVING, new ResourceLocation("kagic:entities.rose_quartz.living"), event);
		registerSound(ROSE_QUARTZ_HURT, new ResourceLocation("kagic:entities.rose_quartz.hurt"), event);
		registerSound(ROSE_QUARTZ_OBEY, new ResourceLocation("kagic:entities.rose_quartz.obey"), event);
		registerSound(ROSE_QUARTZ_DEATH, new ResourceLocation("kagic:entities.rose_quartz.death"), event);
		registerSound(LAPIS_LAZULI_HURT, new ResourceLocation("kagic:entities.lapis_lazuli.hurt"), event);
		registerSound(LAPIS_LAZULI_OBEY, new ResourceLocation("kagic:entities.lapis_lazuli.obey"), event);
		registerSound(LAPIS_LAZULI_DEATH, new ResourceLocation("kagic:entities.lapis_lazuli.death"), event);
		registerSound(AGATE_HURT, new ResourceLocation("kagic:entities.agate.hurt"), event);
		registerSound(AGATE_OBEY, new ResourceLocation("kagic:entities.agate.obey"), event);
		registerSound(AGATE_DEATH, new ResourceLocation("kagic:entities.agate.death"), event);
		registerSound(YELLOW_DIAMOND_INTRO, new ResourceLocation("kagic:entities.yellow_diamond.intro"), event);
		registerSound(YELLOW_DIAMOND_OUTRO, new ResourceLocation("kagic:entities.yellow_diamond.outro"), event);
		registerSound(YELLOW_DIAMOND_LIVING, new ResourceLocation("kagic:entities.yellow_diamond.living"), event);
		registerSound(YELLOW_DIAMOND_HURT, new ResourceLocation("kagic:entities.yellow_diamond.hurt"), event);
		registerSound(YELLOW_DIAMOND_DEATH, new ResourceLocation("kagic:entities.yellow_diamond.death"), event);
		registerSound(BLUE_DIAMOND_INTRO, new ResourceLocation("kagic:entities.blue_diamond.intro"), event);
		registerSound(BLUE_DIAMOND_OUTRO, new ResourceLocation("kagic:entities.blue_diamond.outro"), event);
		registerSound(BLUE_DIAMOND_LIVING, new ResourceLocation("kagic:entities.blue_diamond.living"), event);
		registerSound(BLUE_DIAMOND_HURT, new ResourceLocation("kagic:entities.blue_diamond.hurt"), event);
		registerSound(BLUE_DIAMOND_DEATH, new ResourceLocation("kagic:entities.blue_diamond.death"), event);
		registerSound(AQUAMARINE_LIVING, new ResourceLocation("kagic:entities.aquamarine.living"), event);
		registerSound(AQUAMARINE_HURT, new ResourceLocation("kagic:entities.aquamarine.hurt"), event);
		registerSound(AQUAMARINE_OBEY, new ResourceLocation("kagic:entities.aquamarine.obey"), event);
		registerSound(AQUAMARINE_DEATH, new ResourceLocation("kagic:entities.aquamarine.death"), event);
		registerSound(GARNET_DEATH, new ResourceLocation("kagic:entities.garnet.death"), event);
		registerSound(GARNET_HURT, new ResourceLocation("kagic:entities.garnet.hurt"), event);
		registerSound(GARNET_OBEY, new ResourceLocation("kagic:entities.garnet.obey"), event);
		registerSound(HESSONITE_DEATH, new ResourceLocation("kagic:entities.hessonite.death"), event);
		registerSound(HESSONITE_HURT, new ResourceLocation("kagic:entities.hessonite.hurt"), event);
		registerSound(HESSONITE_LIVING, new ResourceLocation("kagic:entities.hessonite.living"), event);
		registerSound(HESSONITE_OBEY, new ResourceLocation("kagic:entities.hessonite.obey"), event);
		registerSound(HESSONITE_TELEPORT_START, new ResourceLocation("kagic:entities.hessonite.teleport.start"), event);
		registerSound(HESSONITE_TELEPORT_END, new ResourceLocation("kagic:entities.hessonite.teleport.end"), event);
		registerSound(MALACHITE_DEATH, new ResourceLocation("kagic:entities.malachite.death"), event);
		registerSound(MALACHITE_HURT, new ResourceLocation("kagic:entities.malachite.hurt"), event);
		registerSound(MALACHITE_OBEY, new ResourceLocation("kagic:entities.malachite.obey"), event);
		registerSound(RHODONITE_DEATH, new ResourceLocation("kagic:entities.rhodonite.death"), event);
		registerSound(RHODONITE_HURT, new ResourceLocation("kagic:entities.rhodonite.hurt"), event);
		registerSound(RHODONITE_OBEY, new ResourceLocation("kagic:entities.rhodonite.obey"), event);
		registerSound(RUTILE_DEATH, new ResourceLocation("kagic:entities.rutile.death"), event);
		registerSound(RUTILE_HURT, new ResourceLocation("kagic:entities.rutile.hurt"), event);
		registerSound(RUTILE_LIVING, new ResourceLocation("kagic:entities.rutile.living"), event);
		registerSound(RUTILE_OBEY, new ResourceLocation("kagic:entities.rutile.obey"), event);
		registerSound(TOPAZ_STEP, new ResourceLocation("kagic:entities.topaz.step"), event);
		registerSound(TOPAZ_OBEY, new ResourceLocation("kagic:entities.topaz.obey"), event);
		registerSound(TOPAZ_DEATH, new ResourceLocation("kagic:entities.topaz.death"), event);
		registerSound(ZIRCON_DEATH, new ResourceLocation("kagic:entities.zircon.death"), event);
		registerSound(ZIRCON_HURT, new ResourceLocation("kagic:entities.zircon.hurt"), event);
		registerSound(ZIRCON_OBEY, new ResourceLocation("kagic:entities.zircon.obey"), event);
		registerSound(STEVEN_HELLO, new ResourceLocation("kagic:entities.steven.hello"), event);
		registerSound(STEVEN_LIVING, new ResourceLocation("kagic:entities.steven.living"), event);
		registerSound(STEVEN_HURT, new ResourceLocation("kagic:entities.steven.hurt"), event);
		registerSound(STEVEN_PROTECT, new ResourceLocation("kagic:entities.steven.protect"), event);
		registerSound(STEVEN_DEATH, new ResourceLocation("kagic:entities.steven.death"), event);
		registerSound(STEVEN_SNEEZE, new ResourceLocation("kagic:entities.steven.sneeze"), event);
		registerSound(CONNIE_HELLO, new ResourceLocation("kagic:entities.connie.hello"), event);
		registerSound(CONNIE_LIVING, new ResourceLocation("kagic:entities.connie.living"), event);
		registerSound(CONNIE_HURT, new ResourceLocation("kagic:entities.connie.hurt"), event);
		registerSound(CONNIE_PROTECT, new ResourceLocation("kagic:entities.connie.protect"), event);
		registerSound(CONNIE_DEATH, new ResourceLocation("kagic:entities.connie.death"), event);
		registerSound(CORRUPTED_QUARTZ_AMBIENT, new ResourceLocation("kagic:entities.corrupted_quartz.living"), event);
		registerSound(CORRUPTED_QUARTZ_HURT, new ResourceLocation("kagic:entities.corrupted_quartz.hurt"), event);
		registerSound(CORRUPTED_QUARTZ_DEATH, new ResourceLocation("kagic:entities.corrupted_quartz.death"), event);
		registerSound(TONGUE_MONSTER_AMBIENT, new ResourceLocation("kagic:entities.tongue_monster.living"), event);
		registerSound(TONGUE_MONSTER_HURT, new ResourceLocation("kagic:entities.tongue_monster.hurt"), event);
		registerSound(TONGUE_MONSTER_DEATH, new ResourceLocation("kagic:entities.tongue_monster.death"), event);
		registerSound(WARP_PAD, new ResourceLocation(KAGIC.MODID, "warp_pad"), event);
		for (int i = 0; i < JAM_BUD_SONG_PARTS.length; ++i) {
			int part = i + 1; JAM_BUD_SONG_PARTS[i] = new SoundEvent(new ResourceLocation("kagic:song.jam_buds_" + part));
			registerSound(JAM_BUD_SONG_PARTS[i], new ResourceLocation("kagic:song.jam_buds_" + part), event);
		}
	}
	
	private static void registerSound(SoundEvent sound, ResourceLocation location, RegistryEvent.Register<SoundEvent> event) {
		sound.setRegistryName(location);
		event.getRegistry().register(sound);
	}
}
