package mod.akrivus.kagic.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModSounds {
	public static final SoundEvent RECORD_LITTLE_PERIDOT = new SoundEvent(new ResourceLocation("kagic:records.little_peridot"));
	public static final SoundEvent RECORD_ROSES_FOUNTAIN = new SoundEvent(new ResourceLocation("kagic:records.roses_fountain"));
	public static final SoundEvent RECORD_LAPIS_FLIGHT = new SoundEvent(new ResourceLocation("kagic:records.lapis_flight"));
	public static final SoundEvent RECORD_THE_BREAKING_POINT = new SoundEvent(new ResourceLocation("kagic:records.the_breaking_point"));
	public static final SoundEvent RECORD_DUEL_OF_THE_QUARTZ = new SoundEvent(new ResourceLocation("kagic:records.duel_of_the_quartz"));
	public static final SoundEvent RECORD_YELLOW_DIAMOND = new SoundEvent(new ResourceLocation("kagic:records.yellow_diamond"));
	public static final SoundEvent RECORD_BLUE_DIAMOND = new SoundEvent(new ResourceLocation("kagic:records.blue_diamond"));
	public static final SoundEvent RECORD_WHATS_THE_USE_OF_FEELING_BLUE = new SoundEvent(new ResourceLocation("kagic:records.whats_the_use_of_feeling_blue"));

	public static final SoundEvent BLOCK_GEM_SEED_HATCH = new SoundEvent(new ResourceLocation("kagic:blocks.gem_seed_hatch"));
	public static final SoundEvent BLOCK_INJECTOR_OPEN = new SoundEvent(new ResourceLocation("kagic:blocks.injector_open"));
	public static final SoundEvent BLOCK_INJECTOR_CLOSE = new SoundEvent(new ResourceLocation("kagic:blocks.injector_close"));
	public static final SoundEvent BLOCK_INJECTOR_FIRE = new SoundEvent(new ResourceLocation("kagic:blocks.injector_fire"));
	public static final SoundEvent GEM_POOF = new SoundEvent(new ResourceLocation("kagic:entities.gem.poof"));
	public static final SoundEvent GEM_SHATTER = new SoundEvent(new ResourceLocation("kagic:entities.gem.shatter"));

	public static final SoundEvent SLAG_EAT = new SoundEvent(new ResourceLocation("kagic:entities.slag.eat"));
	public static final SoundEvent PEPO_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.pepo.living"));
	public static final SoundEvent RUBY_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.ruby.living"));
	public static final SoundEvent RUBY_HURT = new SoundEvent(new ResourceLocation("kagic:entities.ruby.hurt"));
	public static final SoundEvent RUBY_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.ruby.obey"));
	public static final SoundEvent RUBY_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.ruby.death"));
	public static final SoundEvent RUBY_EXPLODE = new SoundEvent(new ResourceLocation("kagic:entities.ruby.explode"));
	public static final SoundEvent SAPPHIRE_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.living"));
	public static final SoundEvent SAPPHIRE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.hurt"));
	public static final SoundEvent SAPPHIRE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.obey"));
	public static final SoundEvent SAPPHIRE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.sapphire.death"));
	public static final SoundEvent PADPARADSCHA_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.padparadscha.living"));
	public static final SoundEvent PERIDOT_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.peridot.living"));
	public static final SoundEvent PERIDOT_HURT = new SoundEvent(new ResourceLocation("kagic:entities.peridot.hurt"));
	public static final SoundEvent PERIDOT_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.peridot.obey"));
	public static final SoundEvent PERIDOT_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.peridot.death"));
	public static final SoundEvent PEARL_HURT = new SoundEvent(new ResourceLocation("kagic:entities.pearl.hurt"));
	public static final SoundEvent PEARL_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.pearl.obey"));
	public static final SoundEvent PEARL_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.pearl.death"));
	public static final SoundEvent BISMUTH_HURT = new SoundEvent(new ResourceLocation("kagic:entities.bismuth.hurt"));
	public static final SoundEvent BISMUTH_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.bismuth.obey"));
	public static final SoundEvent BISMUTH_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.bismuth.death"));
	public static final SoundEvent JASPER_HURT = new SoundEvent(new ResourceLocation("kagic:entities.jasper.hurt"));
	public static final SoundEvent JASPER_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.jasper.obey"));
	public static final SoundEvent JASPER_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.jasper.death"));
	public static final SoundEvent AMETHYST_HURT = new SoundEvent(new ResourceLocation("kagic:entities.amethyst.hurt"));
	public static final SoundEvent AMETHYST_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.amethyst.obey"));
	public static final SoundEvent AMETHYST_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.amethyst.death"));
	public static final SoundEvent ROSE_QUARTZ_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.living"));
	public static final SoundEvent ROSE_QUARTZ_HURT = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.hurt"));
	public static final SoundEvent ROSE_QUARTZ_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.obey"));
	public static final SoundEvent ROSE_QUARTZ_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.rose_quartz.death"));
	public static final SoundEvent LAPIS_LAZULI_HURT = new SoundEvent(new ResourceLocation("kagic:entities.lapis_lazuli.hurt"));
	public static final SoundEvent LAPIS_LAZULI_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.lapis_lazuli.obey"));
	public static final SoundEvent LAPIS_LAZULI_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.lapis_lazuli.death"));
	public static final SoundEvent AGATE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.agate.hurt"));
	public static final SoundEvent AGATE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.agate.obey"));
	public static final SoundEvent AGATE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.agate.death"));
	public static final SoundEvent YELLOW_DIAMOND_INTRO = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.intro"));
	public static final SoundEvent YELLOW_DIAMOND_OUTRO = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.outro"));
	public static final SoundEvent YELLOW_DIAMOND_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.living"));
	public static final SoundEvent YELLOW_DIAMOND_HURT = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.hurt"));
	public static final SoundEvent YELLOW_DIAMOND_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.yellow_diamond.death"));
	public static final SoundEvent BLUE_DIAMOND_INTRO = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.intro"));
	public static final SoundEvent BLUE_DIAMOND_OUTRO = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.outro"));
	public static final SoundEvent BLUE_DIAMOND_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.living"));
	public static final SoundEvent BLUE_DIAMOND_HURT = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.hurt"));
	public static final SoundEvent BLUE_DIAMOND_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.blue_diamond.death"));
	public static final SoundEvent AQUAMARINE_LIVING = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.living"));
	public static final SoundEvent AQUAMARINE_HURT = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.hurt"));
	public static final SoundEvent AQUAMARINE_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.obey"));
	public static final SoundEvent AQUAMARINE_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.aquamarine.death"));
	public static final SoundEvent TOPAZ_STEP = new SoundEvent(new ResourceLocation("kagic:entities.topaz.step"));
	public static final SoundEvent TOPAZ_OBEY = new SoundEvent(new ResourceLocation("kagic:entities.topaz.obey"));
	public static final SoundEvent TOPAZ_DEATH = new SoundEvent(new ResourceLocation("kagic:entities.topaz.death"));
	public static final SoundEvent WARP_PAD = new SoundEvent(new ResourceLocation(KAGIC.MODID, "warp_pad"));
	
	public static void register() {
		GameRegistry.register(RECORD_LITTLE_PERIDOT, new ResourceLocation("kagic:records.little_peridot"));
		GameRegistry.register(RECORD_ROSES_FOUNTAIN, new ResourceLocation("kagic:records.roses_fountain"));
		GameRegistry.register(RECORD_LAPIS_FLIGHT, new ResourceLocation("kagic:records.lapis_flight"));
		GameRegistry.register(RECORD_THE_BREAKING_POINT, new ResourceLocation("kagic:records.the_breaking_point"));
		GameRegistry.register(RECORD_DUEL_OF_THE_QUARTZ, new ResourceLocation("kagic:records.duel_of_the_quartz"));
		GameRegistry.register(RECORD_YELLOW_DIAMOND, new ResourceLocation("kagic:records.yellow_diamond"));
		GameRegistry.register(RECORD_BLUE_DIAMOND, new ResourceLocation("kagic:records.blue_diamond"));
		GameRegistry.register(RECORD_WHATS_THE_USE_OF_FEELING_BLUE, new ResourceLocation("kagic:records.whats_the_use_of_feeling_blue"));
		GameRegistry.register(BLOCK_GEM_SEED_HATCH, new ResourceLocation("kagic:blocks.gem_seed_hatch"));
		GameRegistry.register(BLOCK_INJECTOR_OPEN, new ResourceLocation("kagic:blocks.injector_open"));
		GameRegistry.register(BLOCK_INJECTOR_CLOSE, new ResourceLocation("kagic:blocks.injector_close"));
		GameRegistry.register(BLOCK_INJECTOR_FIRE, new ResourceLocation("kagic:blocks.injector_fire"));
		GameRegistry.register(GEM_POOF, new ResourceLocation("kagic:entities.gem.poof"));
		GameRegistry.register(GEM_SHATTER, new ResourceLocation("kagic:entities.gem.shatter"));
		GameRegistry.register(SLAG_EAT, new ResourceLocation("kagic:entities.slag.eat"));
		GameRegistry.register(PEPO_LIVING, new ResourceLocation("kagic:entities.pepo.living"));
		GameRegistry.register(RUBY_LIVING, new ResourceLocation("kagic:entities.ruby.living"));
		GameRegistry.register(RUBY_HURT, new ResourceLocation("kagic:entities.ruby.hurt"));
		GameRegistry.register(RUBY_OBEY, new ResourceLocation("kagic:entities.ruby.obey"));
		GameRegistry.register(RUBY_DEATH, new ResourceLocation("kagic:entities.ruby.death"));
		GameRegistry.register(RUBY_EXPLODE, new ResourceLocation("kagic:entities.ruby.explode"));
		GameRegistry.register(SAPPHIRE_LIVING, new ResourceLocation("kagic:entities.sapphire.living"));
		GameRegistry.register(SAPPHIRE_HURT, new ResourceLocation("kagic:entities.sapphire.hurt"));
		GameRegistry.register(SAPPHIRE_OBEY, new ResourceLocation("kagic:entities.sapphire.obey"));
		GameRegistry.register(SAPPHIRE_DEATH, new ResourceLocation("kagic:entities.sapphire.death"));
		GameRegistry.register(PADPARADSCHA_LIVING, new ResourceLocation("kagic:entities.padparadscha.living"));
		GameRegistry.register(PERIDOT_LIVING, new ResourceLocation("kagic:entities.peridot.living"));
		GameRegistry.register(PERIDOT_HURT, new ResourceLocation("kagic:entities.peridot.hurt"));
		GameRegistry.register(PERIDOT_OBEY, new ResourceLocation("kagic:entities.peridot.obey"));
		GameRegistry.register(PERIDOT_DEATH, new ResourceLocation("kagic:entities.peridot.death"));
		GameRegistry.register(PEARL_HURT, new ResourceLocation("kagic:entities.pearl.hurt"));
		GameRegistry.register(PEARL_OBEY, new ResourceLocation("kagic:entities.pearl.obey"));
		GameRegistry.register(PEARL_DEATH, new ResourceLocation("kagic:entities.pearl.death"));
		GameRegistry.register(BISMUTH_HURT, new ResourceLocation("kagic:entities.bismuth.hurt"));
		GameRegistry.register(BISMUTH_OBEY, new ResourceLocation("kagic:entities.bismuth.obey"));
		GameRegistry.register(BISMUTH_DEATH, new ResourceLocation("kagic:entities.bismuth.death"));
		GameRegistry.register(JASPER_HURT, new ResourceLocation("kagic:entities.jasper.hurt"));
		GameRegistry.register(JASPER_OBEY, new ResourceLocation("kagic:entities.jasper.obey"));
		GameRegistry.register(JASPER_DEATH, new ResourceLocation("kagic:entities.jasper.death"));
		GameRegistry.register(AMETHYST_HURT, new ResourceLocation("kagic:entities.amethyst.hurt"));
		GameRegistry.register(AMETHYST_OBEY, new ResourceLocation("kagic:entities.amethyst.obey"));
		GameRegistry.register(AMETHYST_DEATH, new ResourceLocation("kagic:entities.amethyst.death"));
		GameRegistry.register(ROSE_QUARTZ_LIVING, new ResourceLocation("kagic:entities.rose_quartz.living"));
		GameRegistry.register(ROSE_QUARTZ_HURT, new ResourceLocation("kagic:entities.rose_quartz.hurt"));
		GameRegistry.register(ROSE_QUARTZ_OBEY, new ResourceLocation("kagic:entities.rose_quartz.obey"));
		GameRegistry.register(ROSE_QUARTZ_DEATH, new ResourceLocation("kagic:entities.rose_quartz.death"));
		GameRegistry.register(LAPIS_LAZULI_HURT, new ResourceLocation("kagic:entities.lapis_lazuli.hurt"));
		GameRegistry.register(LAPIS_LAZULI_OBEY, new ResourceLocation("kagic:entities.lapis_lazuli.obey"));
		GameRegistry.register(LAPIS_LAZULI_DEATH, new ResourceLocation("kagic:entities.lapis_lazuli.death"));
		GameRegistry.register(AGATE_HURT, new ResourceLocation("kagic:entities.agate.hurt"));
		GameRegistry.register(AGATE_OBEY, new ResourceLocation("kagic:entities.agate.obey"));
		GameRegistry.register(AGATE_DEATH, new ResourceLocation("kagic:entities.agate.death"));
		GameRegistry.register(YELLOW_DIAMOND_INTRO, new ResourceLocation("kagic:entities.yellow_diamond.intro"));
		GameRegistry.register(YELLOW_DIAMOND_OUTRO, new ResourceLocation("kagic:entities.yellow_diamond.outro"));
		GameRegistry.register(YELLOW_DIAMOND_LIVING, new ResourceLocation("kagic:entities.yellow_diamond.living"));
		GameRegistry.register(YELLOW_DIAMOND_HURT, new ResourceLocation("kagic:entities.yellow_diamond.hurt"));
		GameRegistry.register(YELLOW_DIAMOND_DEATH, new ResourceLocation("kagic:entities.yellow_diamond.death"));
		GameRegistry.register(BLUE_DIAMOND_INTRO, new ResourceLocation("kagic:entities.blue_diamond.intro"));
		GameRegistry.register(BLUE_DIAMOND_OUTRO, new ResourceLocation("kagic:entities.blue_diamond.outro"));
		GameRegistry.register(BLUE_DIAMOND_LIVING, new ResourceLocation("kagic:entities.blue_diamond.living"));
		GameRegistry.register(BLUE_DIAMOND_HURT, new ResourceLocation("kagic:entities.blue_diamond.hurt"));
		GameRegistry.register(BLUE_DIAMOND_DEATH, new ResourceLocation("kagic:entities.blue_diamond.death"));
		GameRegistry.register(AQUAMARINE_LIVING, new ResourceLocation("kagic:entities.aquamarine.living"));
		GameRegistry.register(AQUAMARINE_HURT, new ResourceLocation("kagic:entities.aquamarine.hurt"));
		GameRegistry.register(AQUAMARINE_OBEY, new ResourceLocation("kagic:entities.aquamarine.obey"));
		GameRegistry.register(AQUAMARINE_DEATH, new ResourceLocation("kagic:entities.aquamarine.death"));
		GameRegistry.register(TOPAZ_STEP, new ResourceLocation("kagic:entities.topaz.step"));
		GameRegistry.register(TOPAZ_OBEY, new ResourceLocation("kagic:entities.topaz.obey"));
		GameRegistry.register(TOPAZ_DEATH, new ResourceLocation("kagic:entities.topaz.death"));
		GameRegistry.register(WARP_PAD, new ResourceLocation(KAGIC.MODID, "warp_pad"));
	}
}
